- name: catalogue service
  hosts: catalogue
  become: true
  vars:
    MONGODB_HOST: "mongodb.daws-90s.shop"
  tasks:
    - name: enable nodejs:20 module stream
      ansible.builtin.command: dnf module enable nodejs:20 -y
      changed_when: false

    - name: Install nodejs runtime
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Create the system user 
      ansible.builtin.user:
        name: roboshop
        system: true     
        home: /app     
        shell: /sbin/nologin    
        state: present

    - name: remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: remove the catalogue.zip in tmp directory
      ansible.builtin.file:
        path: /tmp/catalogue.zip
        state: absent

    - name: Create app directory with ownership
      ansible.builtin.file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop

    - name: Download and extract catalogue artifact
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /app
        remote_src: true
        owner: roboshop
        group: roboshop

    - name: Install npm dependencies 
      community.general.npm:
        path: /app
        state: present

    - name: Copy file catalogue service template
      ansible.builtin.template:
        src: catalogue.service.j2
        dest: /etc/systemd/system/catalogue.service  
        mode: '0644'

    - name: copy the mongo repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install mongodb client
      ansible.builtin.package:
        name: mongodb-mongosh
        state: present

    - name: check the catalogue schema exist or not
      ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" --eval "db.adminCommand('listDatabases').databases.map(db => db.name).includes('catalogue')"
      register: catalogue_output
      changed_when: false

    - name: print catalogue output
      ansible.builtin.debug: 
        msg: "{{ catalogue_output.stdout }}"

    - name: load products into mongodb if not present
      ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
      when: "'false' in catalogue_output.stdout"
      tags:
        - mongodb

    - name: daemon reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: enable and start catalogue service
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: yes

       

 



      









