[local]
localhost

[mongodb]
mongodb.daws-90s.shop

[redis]
redis.daws-90s.shop

[mysql]
mysql.daws-90s.shop

[catalogue]
catalogue.daws-90s.shop

[rabbitmq]
rabbitmq.daws-90s.shop

[user]
user.daws-90s.shop

[cart]
cart.daws-90s.shop

[shipping]
shipping.daws-90s.shop

[payment]
payment.daws-90s.shop

[frontend]
frontend.daws-90s.shop