---
- name: roboshop instance management
  hosts: localhost
  connection: local
  vars:
    domain_name: daws-90s.shop
    action: create
    instances:
      - mongodb
      - redis
      - rabbitmq
      - catalogue
      - frontend
    ami_id: "ami-0220d79f3f480ecf5"

  tasks:
    - name: create ec2-instance
      amazon.aws.ec2_instance:
        name: "roboshop-{{ item }}"
        instance_type: t3.micro
        image_id: "{{ ami_id }}"
        security_groups:
          - "roboshop-{{ item }}"
          - roboshop-common
        state: running
      loop: "{{ instances }}"
      register: ec2_output

    - name: print output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"

    - name: print private ip details
      ansible.builtin.debug:
        msg: "instance name: {{ item.item }} privateip: {{ item.instances[0].private_ip_address }}"
      loop: "{{ ec2_output.results }}"

    - name: create route53 record frontend (public ip)
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        overwrite: true
      loop: "{{ ec2_output.results }}"
      when:
        - item.item == "frontend"
        - action == "create"

    - name: create route53 records backend (private ip)
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
      loop: "{{ ec2_output.results }}"
      when:
        - item.item != "frontend"
        - action == "create"

- name: delete r53 records
  amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}.{{ domain_name }}" # mongodb.daws90s.shop
      ttl: 1
      type: A
  loop: "{{ instances  }}"  
  when: action == "delete"
